version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: compoundsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: compoundsdb
      DB_PORT: 5432
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: .
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:
